apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- traefik-config.yaml
- storage/local-path-config.yaml
- storage/project-assets-pvc.yaml
- gpu/device-plugin.yaml
- base
- smoke-app
- apps/asset-api
- apps/reference-time
- tekton
