apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: project-assets
  namespace: gpmidi-ml
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 50Gi
