apiVersion: v1
kind: ServiceAccount
metadata:
  name: sheetsage2-controller
  namespace: gpmidi-ml
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sheetsage2-worker
  namespace: gpmidi-ml
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sheetsage2-controller
  namespace: gpmidi-ml
rules:
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["create", "get", "list", "delete"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sheetsage2-controller
  namespace: gpmidi-ml
subjects:
- kind: ServiceAccount
  name: sheetsage2-controller
  namespace: gpmidi-ml
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: sheetsage2-controller
