apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sheetsage2-data
  namespace: gpmidi-ml
  labels:
    app: sheetsage2-service
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sheetsage2-models
  namespace: gpmidi-ml
  labels:
    app: sheetsage2-service
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: local-path
  resources:
    requests:
      storage: 8Gi
