apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: reference-time-data
  namespace: gpmidi-ml
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
