apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-build
  namespace: gpmidi-ml
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-deploy
  namespace: gpmidi-ml
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tekton-deploy
  namespace: gpmidi-ml
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "patch", "update"]
- apiGroups: ["apps"]
  resources: ["deployments/status"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tekton-deploy
  namespace: gpmidi-ml
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tekton-deploy
subjects:
- kind: ServiceAccount
  name: tekton-deploy
  namespace: gpmidi-ml
---
# EventListener needs to create PipelineRuns in gpmidi-ml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tekton-triggers-el
  namespace: gpmidi-ml
rules:
- apiGroups: ["tekton.dev"]
  resources: ["pipelineruns"]
  verbs: ["create"]
- apiGroups: ["triggers.tekton.dev"]
  resources: ["eventlisteners", "triggerbindings", "triggertemplates"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tekton-triggers-el
  namespace: gpmidi-ml
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tekton-triggers-el
subjects:
- kind: ServiceAccount
  name: tekton-triggers-el
  namespace: gpmidi-ml
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-triggers-el
  namespace: gpmidi-ml
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tekton-triggers-el-interceptors
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tekton-triggers-eventlistener-clusterroles
subjects:
- kind: ServiceAccount
  name: tekton-triggers-el
  namespace: gpmidi-ml
