apiVersion: v1
kind: LimitRange
metadata:
  name: gpmidi-ml-limits
  namespace: gpmidi-ml
spec:
  limits:
  - type: Container
    default:
      cpu: 500m
      memory: 512Mi
    defaultRequest:
      cpu: 100m
      memory: 128Mi
    max:
      cpu: "8"
      memory: 16Gi
  - type: Pod
    max:
      cpu: "10"
      memory: 20Gi
